$str1="ATGHGGDTTSFGA";
$sub = "F";
$i = index $str1, $sub;
print "$i \n";
$e= lc $str1;
print "$e\n";
$f = ucfirst $e;
print "$f \n";
@array = qw/This is an array/; 
print "@array\n";
unshift(@array, "A","R"); 
print "\@array = @array\n"; 
